#!/bin/bash
cd /root
clear
sleep 1
echo -e "====================================================================================================================="
echo
echo -e "\t 欢迎使用 “\033[32m oj8k \033[0m” 一键ssr aria2 op综合脚本"
echo
echo -e "\t 本脚本由西门吹雪、Dios、花下砂、胡歌、阿哇、普洱、幸福简单等妖友提供的脚本修改整合而成"
echo
echo -e "\t 只是为了方便妖友使用（如有侵权，请联系我删除 邮箱：6578093@Gmail.com）"
echo
echo -e "\t 感谢西门吹雪、Dios、花下砂、胡歌、普洱、阿哇、幸福简单等妖友"
echo
echo -e "====================================================================================================================="
echo
echo -e "\033[35m 1.搭建锐速 BBR \033[0m"
echo
echo -e "\033[35m 2.搭建Aria2 \033[0m"
echo
echo -e "\033[35m 3.搭建多端口SSR \033[0m"
echo
echo -e "\033[35m 4.搭建多用户SSR \033[0m"
echo
echo -e "\033[35m 5.搭建v2ray（by ERBING）\033[0m"
echo
echo -e "\033[35m 6.搭建v2ray （by 233blog） \033[0m"
echo
echo -e "\033[35m 7.搭建SEVPN（by寂寞爱上海）\033[0m"
echo
echo -e "\033[35m 8.搭建快云流控（十一）\033[0m"
echo
echo -e  "\033[35m 请选择 [ 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10, 11 ] 进行下一步安装！\033[0m
 
 >请选择安装类型: "
read az
  case $az in
    1) wget -q http://520lsj.cn/bbr && bash bbr
       ;;
    2) wget -q http://520lsj.cn/aria2 && bash aria2
       ;;
    3) wget -q http://520lsj.cn/ssrs && bash ssrs
       ;;
    4) wget http://520lsj.cn/ssr2.zip && unzip ssr2.zip && bash ssr2
       ;;
    5) cd ~;rm -rf v2ray.*;wget https://raw.githubusercontent.com/oj8k/oj8k/master/v2ray/v2ray.sh;chmod 777 v2ray.sh;./v2ray.sh 2>&1 | tee v2ray.log;rm -rf v2ray.sh && bash v2ray
       ;;
   	6) wget -q http://520lsj.cn/sevpn && bash sevpn
	   ;;
	6) wget -q http://520lsj.cn/sevpn && bash sevpn
	   ;;
	7) wget -q http://520lsj.cn/vpns && bash vpns
	   ;;
    *)  echo -e "\033[31m 错误：只能选择[ 1 , 2 , 3, 4 , 5 , 6 , 7 , 8 , 9 , 10 ]！！\033[0m"
       ;; 
  esac
